# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.runs/synth_1/anton_mcu_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 2
set_param synth.incrementalSynthesisCache C:/Users/Harid/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-21136-Harid-PC/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.cache/wt} [current_project]
set_property parent.project_path {D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-a7-35:part0:1.0 [current_project]
set_property ip_output_repo {d:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files {{D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.srcs/sources_1/bd/Instr_ROM/ip/Instr_ROM_blk_mem_gen_0_0/instr_mem_contents.coe}}
add_files {{D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.srcs/sources_1/bd/BRAM_32B_SDP/ip/BRAM_32B_SDP_blk_mem_gen_0_0/reg_file.coe}}
add_files {{D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.srcs/sources_1/bd/Data_RAM/ip/Data_RAM_blk_mem_gen_0_0/data_mem.coe}}
read_verilog -library xil_defaultlib -sv {
  {D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.srcs/sources_1/new/alu.sv}
  {D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.srcs/sources_1/new/branch_control.sv}
  {D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.srcs/sources_1/new/core_top.sv}
  {D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.srcs/sources_1/new/data_mem.sv}
  {D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.srcs/sources_1/new/data_mmu.sv}
  {D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.srcs/sources_1/new/instr_decode.sv}
  {D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.srcs/sources_1/new/instr_mem.sv}
  {D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.srcs/sources_1/new/instruction_fetch.sv}
  {D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.srcs/sources_1/new/program_counter.sv}
  {D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.srcs/sources_1/new/register_file.sv}
  {D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.srcs/sources_1/new/anton_mcu_top.sv}
  {D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.srcs/sources_1/new/gpio.sv}
  {D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.srcs/sources_1/new/pll.sv}
}
add_files {{D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.srcs/sources_1/bd/Instr_ROM/Instr_ROM.bd}}
set_property used_in_implementation false [get_files -all {{d:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.gen/sources_1/bd/Instr_ROM/ip/Instr_ROM_blk_mem_gen_0_0/Instr_ROM_blk_mem_gen_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.gen/sources_1/bd/Instr_ROM/Instr_ROM_ooc.xdc}}]

add_files {{D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.srcs/sources_1/bd/BRAM_32B_SDP/BRAM_32B_SDP.bd}}
set_property used_in_implementation false [get_files -all {{d:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.gen/sources_1/bd/BRAM_32B_SDP/ip/BRAM_32B_SDP_blk_mem_gen_0_0/BRAM_32B_SDP_blk_mem_gen_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.gen/sources_1/bd/BRAM_32B_SDP/BRAM_32B_SDP_ooc.xdc}}]

add_files {{D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.srcs/sources_1/bd/Data_RAM/Data_RAM.bd}}
set_property used_in_implementation false [get_files -all {{d:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.gen/sources_1/bd/Data_RAM/ip/Data_RAM_blk_mem_gen_0_0/Data_RAM_blk_mem_gen_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.gen/sources_1/bd/Data_RAM/Data_RAM_ooc.xdc}}]

add_files {{D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.srcs/sources_1/bd/PLL/PLL.bd}}
set_property used_in_implementation false [get_files -all {{d:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.gen/sources_1/bd/PLL/ip/PLL_clk_wiz_0_0/PLL_clk_wiz_0_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.gen/sources_1/bd/PLL/ip/PLL_clk_wiz_0_0/PLL_clk_wiz_0_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.gen/sources_1/bd/PLL/ip/PLL_clk_wiz_0_0/PLL_clk_wiz_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.gen/sources_1/bd/PLL/PLL_ooc.xdc}}]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.srcs/constrs_1/new/Arty-A7-35-Master.xdc}}
set_property used_in_implementation false [get_files {{D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.srcs/constrs_1/new/Arty-A7-35-Master.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top anton_mcu_top -part xc7a35ticsg324-1L
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef anton_mcu_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file anton_mcu_top_utilization_synth.rpt -pb anton_mcu_top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
