# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Arty-A7-35-Master.xdc

# Block Designs: bd/Instr_ROM/Instr_ROM.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Instr_ROM || ORIG_REF_NAME==Instr_ROM} -quiet] -quiet

# IP: bd/Instr_ROM/ip/Instr_ROM_blk_mem_gen_0_0/Instr_ROM_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Instr_ROM_blk_mem_gen_0_0 || ORIG_REF_NAME==Instr_ROM_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: bd/BRAM_32B_SDP/BRAM_32B_SDP.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BRAM_32B_SDP || ORIG_REF_NAME==BRAM_32B_SDP} -quiet] -quiet

# IP: bd/BRAM_32B_SDP/ip/BRAM_32B_SDP_blk_mem_gen_0_0/BRAM_32B_SDP_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BRAM_32B_SDP_blk_mem_gen_0_0 || ORIG_REF_NAME==BRAM_32B_SDP_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: bd/Data_RAM/Data_RAM.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Data_RAM || ORIG_REF_NAME==Data_RAM} -quiet] -quiet

# IP: bd/Data_RAM/ip/Data_RAM_blk_mem_gen_0_0/Data_RAM_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Data_RAM_blk_mem_gen_0_0 || ORIG_REF_NAME==Data_RAM_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: bd/PLL/PLL.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PLL || ORIG_REF_NAME==PLL} -quiet] -quiet

# IP: bd/PLL/ip/PLL_clk_wiz_0_0/PLL_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PLL_clk_wiz_0_0 || ORIG_REF_NAME==PLL_clk_wiz_0_0} -quiet] -quiet

# XDC: D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.gen/sources_1/bd/Instr_ROM/Instr_ROM_ooc.xdc

# XDC: D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.gen/sources_1/bd/BRAM_32B_SDP/BRAM_32B_SDP_ooc.xdc

# XDC: D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.gen/sources_1/bd/Data_RAM/Data_RAM_ooc.xdc

# XDC: D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.gen/sources_1/bd/PLL/PLL_ooc.xdc
