# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.srcs/sources_1/bd/BRAM_32B_SDP/ip/BRAM_32B_SDP_blk_mem_gen_0_0/BRAM_32B_SDP_blk_mem_gen_0_0.xci
# IP: The module: 'BRAM_32B_SDP_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.gen/sources_1/bd/BRAM_32B_SDP/ip/BRAM_32B_SDP_blk_mem_gen_0_0/BRAM_32B_SDP_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_32B_SDP_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.srcs/sources_1/bd/BRAM_32B_SDP/ip/BRAM_32B_SDP_blk_mem_gen_0_0/BRAM_32B_SDP_blk_mem_gen_0_0.xci
# IP: The module: 'BRAM_32B_SDP_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Harid/College/Win 2020/ECE3003/Project/RISC-V/Vivado Project/rv32i/rv32i.gen/sources_1/bd/BRAM_32B_SDP/ip/BRAM_32B_SDP_blk_mem_gen_0_0/BRAM_32B_SDP_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_32B_SDP_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
